### ISSUE TITLE
How do you manage your day and what tools do you use mostly for being Focused and be Productive  ?

### ISSUE THREAD

**Issue by cyborgboy** [yohix/ama#10]

**Comment by yohix** [comment]
Hi @cyborgboy :wave: 

Productivity Stack

- [**Todoist**]()
- [**Missive Email**]()
- [**Trello**]()
- [**Microsoft Teams**]()
- [**Discord**]()
- [**Telegram**]()
- [**Feedly**]()
- [****]()
- [****]()

**Comment by yohix** [comment]
Hi @cyborgboy :wave: 

I usually land on my Trello Board every morning :sun_behind_large_cloud: 

### My Stack

- **Todoist**
- **Trello**
- **Notion**
- **Google Calendar**
- **Missive Email**
- **Trello**
- **Microsoft Teams**
- **Discord**
- **Telegram**
- **Feedly**
- **Spotify**
- **Figma**
- **Netlify**
- **Zeit**
- **Wakatime**
- **Rescuetime**
- **GitHub**
- **GitLab**

I think I covered my stuff!

**Comment by cyborgboy** [comment]
That's awesome bro 👍 thanks a lot for sharing
