### ISSUE TITLE
How many Bug Bounties you have done till now and what are they?

### ISSUE THREAD

**Issue by cyborgboy** [yohix/ama#12]
How many Bug Bounties you have done till now and what are they?, Please Describe Your Finding without Disclosing the Company Name.

**Comment by yohix** [comment]
I participated in tons of BB programs, but unfortunately, no one gets selected!

But I got **thanks** from lot.

One of my findings is in my college's mobile app, it leaked the Firebase key of development instance, but my college run it as production instance, it leaked ~5000+ students and staff's data including HOD, Principal, etc, The data are very sensible like unhashed passwords, AADHAAR IDs, Personal home address, phone number, email, etc. And this is one of my biggest findings!

**Comment by cyborgboy** [comment]
Yeah yohix , I've read about your firebase finding on your Dev Blog it was very interesting  :D
