### ISSUE TITLE
What you think about github action features?

### ISSUE THREAD

**Issue by vijaysoul** [yohix/ama#6]

**Comment by yohix** [comment]
GitHub's actions are really cool!

You can check my bakes!

- [**yohix/gh-box**](https://github.com/yohix/gh-box)
- [**yohix/todoist-box**](https://github.com/yohix/todoist-box)
- [**yohix/ascii-text**](https://github.com/yohix/ascii-text)
- [**yohix/deploy-surge**](https://github.com/yohix/deploy-surge)

![](https://media0.giphy.com/media/xTiTnBMEz7zAKs57LG/giphy.gif)
