### ISSUE TITLE
How to find a girlfriend? Please Help me playboy

### ISSUE THREAD

**Issue by vijaysoul** [yohix/ama#7]

**Comment by yohix** [comment]
![](https://media1.giphy.com/media/ZdCJ4G17h7lIsrYfLs/giphy.gif)

**Comment by vijaysoul** [comment]
![GitHub Logo](data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAPDw8QDw8PDw8PDw8PDw8PDw8NDQ0NFREWFhURFRUYHSggGBolGxUVITEhJSkrLi4uFx8zODMtNygtLisBCgoKDg0OFxAQFysdGB0rLS0tKy0rLS0tLSstLS0tLS0rLS0rNy0rLS0tKy03LS0tKystLS0tNys3Ky0tKysrK//AABEIAMABBwMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAADAAECBAUGB//EADoQAAICAQMCBAQDBQYHAAAAAAABAgMRBBIhBTETQVFxBiJhkRShsTJCUoHwFSMzYsHRBxYkcnOC4f/EABkBAAMBAQEAAAAAAAAAAAAAAAABAgMEBf/EACIRAQEAAgICAgMBAQAAAAAAAAABAhEDIRIxQVEEEyLBFP/aAAwDAQACEQMRAD8A3ay7SVa4FuuDPOmNY7XqixEr0xLMEa44qSB22KKy2PfaoLLZz+s1Lsf0HdRrx8dyan4pS5zhArNcu0PuZ8E5YS7FuvSvt+YvL6dePFIjPUSb5bYaMG0W6NFFfUtxqXoGqvqKdVPHYmtIn5F+NYWNY/EeSnVpEWq9MgygFhEqRGWQcdIvLgNGgmkFizSSMraHCgq67pKmspYZpwmGTRUjPJwt+lcG00CcTsOqaFWRyl8yOas07XA2djMtiVbambEqAb0wriisR0gpac2p6cHKgi4kxpVApwNidBSuqJ8CZ04g9hddYypLmACqgX6KCFVRp018GkxOBRpJqsNsJxgVpQKgIs7BC0pXpiaFMSnUjR08TDHFnIPXWPqLVXFtho4Sz6HL9e1rnLanwPP+Y148PKh6zWO2XHbyHpozgho6Oxr1U4Mdbd01OojRVgtVxGjAPFDkPYlSLEAUIholSJEiiaRGIRD0mniTQNEkUmiIkmDHTAhkwkZAEx9w9psWVMyupafD3LzLm8jd80cFTJGWLI8Ii6S9Csk6zRlplT0xVtpwbkqwFlGRaLTEdZUvpN2emKt1BNLTn3XyFjSXXp+Q9enHKNKFdBoVV8BFR9CxTUPyORWdQ2wvukZ6cNqU9gi54Ig2bLpjyaeniVaqeTT09WBSI0q9Vv2Vv2OWqr3zy/N5N/4h5aijOqq2mHJ3k6+Kai3p60sFxFSuWCcLORRrpbigkEBhILWAWYLARFdSCplQh0TTAZJKQFobIskFIkhlpNMQ8CWASSY+QbkM5Aek2MsigywoZX1CFeglATgHih9pptz6VfDGdRa2j7A2NKToKtulNfYDnWFLTG/B/QJHSfQ0vCF4ZJ6Z/wCGJRoL3hiVYbCqqSfgllQH2hsKjpGLW0QtmzatOi5XWShAMommyct1t4tKaeS38TrFkX6mfXLg58vddWHqLCQ74Yq+RTQmsHqmW4SM+pYZcqCUWLUEESI1PghO/wBCvSZNjMi5Fay2XkCUJebF5NJgvKwLCwzI27e5YqszyHkVxaMJBJyRVrDPlD2zsDlMH4z8gGpv2plNa1ebSX6keS5i1a9Qy9RbkwP7ShFdnj12yx+hLTdXrm8Rms+nZlTLSbht0+0fBT0N+eC9g13ty5Y6psCwSwPgEo4IyiFwRaC0BbRnENtGwSAtotoXAtoALaM4hto2BALaMG2iA1aMSaRKKJYL2HNfF1Pyxl6NHNwmdt8Q6ffRP1SbOCjIxy9uji9NfTsOlkq6b9lFmruJrEoxDwQowJMZl4ueEJywuXgE7FH+kY/WqdXqIqGm21qXe2xtbV6pLli2uRqS6pXHjO6Xollg7eot9qpP/wBoJ/bJi6H4LSj/ANRqrrZPuoPwYZ9o8/mX4/DmlrxhPjzc5N/fIxMYbUdSUOZQsj7wcl91ku6DXwkuPzyUXpaU0o+JN8JRVk9v6mvp9CsqUkkRtVxnyuVahP8ApFuLWO+Cqq6/KMV/JBqku36F9sriyOu6ayUM1bm15PCUmZ2n0NzSzNVt93FRnP7vt/I7F9u2UZl/Tq7XmEnB/wCXs/dC1o8ct+2H/wAvRn/iam+XqvFa/QLpPhfRwlmLtlL/AMs3/qalfSGnzY5L7GnptGo8IO78HlZJ1UdHp9uNsnx5S5NivlAIUoJDj2NcZqOPkvkMIQhsiEIQwQsCEGgbA+BCDQNgWBxBoGwIcQaACJEUSRGzC1de6El6pnmijtsnF/uya/M9Ra4PPPiPTeFrH/DYty9+zIz+23FfhKufCLunRmwNHTvglutj7GyECxWx+wDDRrOZc/Ty+xYVGQyCQH4n5VTnoE/OX8ngH/Y8X3y/dtmtGJJC8IP21nVdPhDsuStrbdvyruamolhHLau6TsbSbS9BZdemnH/V3V6MpYz35LENZGLw85OW6x1nWfLDRQqzn5vFU8L7NAKJ62LzqbKJRx2rrnCSf0bYY1v4fbuIdTi8IDrZ+HicGnFvlecWcpdo7tRWvDtsp5y3B7ZS+mfJexsdD6PKutxsnKTffMnL835hbb0zuOGPe2vpdcpGjXYcrKEqLMPO1vh+XsbmmvylyPG/bLPCa3GxXMLvM+q0I7TSZOa4dtKDyiRT0d2XguFzthlNXRCFgWCkkIQgBCEOAMMSGAEIQgAA6GHMtLRtsUVmTwkct8S6darY6+JQfd+a9C18Z3zrpTj/ABc/ZnFabq2oUsd0ZZ5d6dXDxbnk0Z0zr/aX812LmnnwgUeo7o4nHDBaS3OV6MGmmlGRarkUFIs1yAWNCDLEDPhYHjcXKi4rikJywVvEIWXhaJiWvs+X34K2n0yKep1m6xR8o8v38ixXropfUWPda3GydJ20L+lgrS0uX2z78lLqvxLRQsyks+/mcrq/jicm/DjPHk8bc/cdjfj4s8o7/T6eMe7RoQwvQ8e1nxLrJresR443ZfHsjKj8f6qqX95KLiu+3K/1CQ8vxbrvJ7b1GmM4NcZwYGi6g4ScJ90+H6o5zpXxxC2CcppJriTeHn0Yb8T+IknW03nhxeSM0Y8dw6vp3Gn1eUWI3GDpK5xWGaFcmu5O6jLCNbSW4kvc3Ec1TI6Kl5jF/RG/DXFzzvaYhCNnOQhCAEIQgBCEIQIQwgAI6GHRGlqXWtEr6ZQ88ZXucLTptkuV2eD0g5XrOj2WN44lzn6+hnyY/Lp/H5Nfyw+uLFLceJY4Zi/D2pseVYvZ+p0uvo31rjtwyEdHCFSaXP0M/l1SzxTqlwWIso1S4LVUgRFjeTiwJLcBiuxlbVWySftkNuTDwqTQqe9OI6x1SOmW6yWHLlLvKXskcp1D4r1Nny6ai2Wf3tuD0m/pMHOUpRTecJvnC9C5pOjVd9kfsacemn7cZHiNXTupaiW50Ty+zsklj2WTtfhT4aujJy1kN8cR8OFb2Ynnlyb8sHpEOn1rtH9Q/wCHil2NNH/04613XHda+FadXp50qpUOTjJXQk5XxxLLw35Pszn9L/wjoTTnZZZjycsJ/Y9ShGK8gkIegbrDLkx9+P8ArjdB8D6arGKoYj2WMhZ9GjRbGVcVHnnHGUdco8lTWVefoZ5QfuuV7DjBbU/oBFK7CKk78kU5F6u46vTr5I/9qOQ6VU7LIx+uX7I7JGvDPly/k3uRIQ2RsmzlOLI2RsgD5FkjkbIHpLIskcjOQj0nkQPcIWz0imOQyPkCSB6iiNkXGSyiaY+RnvTmNbpJUt8boPs/9ysrPlx2yddOCksNZRkdQ6PBpyhmLXOPIyyw+m+HLPVczbxLHqTrkc/1i+7esfK4P7mpotR4kFJcP95fwsjToljUUxpTAwZJsWlxKNpd09pmNhKrBHe2nel39WXKIYRnQmnEs039isGOSy20w0VkErE0KNmDXbOwdVRJxrSKU9TggtcLyg8KttclXWWpJjWauKi3n3Ob1nU98njt5EZZKxx7G1F3kitGbbSXLfCS7tjaTT23yxXFy9X2ivdnYdF6FGjE5/Pb6+UfYnHC5Lz5ZjBug9O8GGZf4k+/+VehqkciydMmpqOHLK5XdSyNkjkWRpPkTZHJFsRpNjZItjZAztjNjZGyIJZGINjiM+R8g9w6ZSRMj5B5HyATyKXJDI+RhzHxH0bd/eRXK7r1OdoqcHujw/NeT9z0HUvcsGFr+lrmUfsK8V9xrhy/FUKZRl24foPKLKzhh+j/ADCRuku/P6mfXy6JaaYFSZYdqfdNA5QT7Mm4rmSP4lolVrPUC6CP4cWhtqV6xPsyc9bhGO9OM4yX7z++QpdLt3UM8AXqpeX58FVVSfm/uWtLpNzS9SVXLSKjbe9kU5Z74Og6X8LQjiVz3P8AhX7K/wBzY6XoI1QWEsvu/NlxmuPHruuTPmt9I1VRgsRiopeSWETI5Fk0YpZFkhkWQCWRmyO4WQB8jDZGyBnbGbGyRbAHbItjNkWwB9wiDHEC3D7gG8W8YWNwtwDcPuAh94JzbyR3E4RNOOfKckYTzw+41qHsr813HrlniRqTI1+kUuUufVGM1h4ff9Trr9P5oydb09T7cS8mZcnH5dz224+TXtk7BthLMq3tsWPR+TDtJnNrXt0bVUhYCzoQP8O/JsD2hJ4AysLEqJepD8NzyTTlDrTZudHp+eOSppqEjU6evnRM9pyvToYyFkjgg2dO3NoSSBtihbzglYvMetpQyLINyGchGJuG3AnIZyACuY28DuI7wA+8i5AdwtwAVsjkhuFuAJbhA8iABbxeIVfEG8QWzXPEHUyl4ha0sc8lYzdK9LdUQ6RGtBVE39M0NoOcCxgTQbCvGTQ1tCfK/mEnEeDwAZ9+jjNYks+5ha/ST03zLMqvPzcP/h1zgDtqUk01lNYaIzxmS8c7i5ai6M1lPKDEdZ0d1Scq+Fn+QKMpdpHJZY6pZfQ0sAngdjKJF2oekv6FfNkoUo1dHEePtGTVhLKFNAq5BHI3YASXKLceUVbQ+nnlFYFkr3LDBOYfWLgz3MVmqUHcyLmA3jOYjGcxtwBzFuAxtw6kA3D7wA24beB3C3ABXMQFyEAf/9k=)
